name: Java CI GitHub

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        - run: curl -O "https://download.java.net/java/GA/jdk12/33/GPL/openjdk-11_windows-x64_bin.zip"
    - name: Set Java
      uses: actions/setup-java@master
      with:
        version: 11
        architecture: x64
        jdkFile: ./openjdk-11_windows-x64_bin.zip
    - name: Build with Maven and test
      run: mvn clean package test -P test
